#!/usr/bin/env node

require('coffee-script');
var parser = require('../../src/helpers/energy2d/e2d-parser'),
    fs = require('fs');

var xmlDir  = __dirname + '/models-xml/',
    jsonDir = __dirname + '/models-json/';

fs.readdirSync(xmlDir).forEach(function (f) {
  console.log('Converting ' + f + '...');
  var xml = fs.readFileSync(xmlDir + f).toString(),
      json = parser.parse(xml);
  f = f.replace('.e2d', '.json');
  fs.writeFileSync(jsonDir + f, JSON.stringify(json, null, 2));
});
