source 'https://rubygems.org'

gem 'rails', '3.2.12'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'thin',  '~> 1.3'

gem "haml",               "~> 4.0.0"
gem "sass",               "~> 3.2.6"
gem 'bourbon',            "~> 3.1.1"
gem 'neat',               "~> 1.2.0"
gem 'rack-rewrite',       "~> 1.2.1"

gem 'ruby-progressbar',   "~> 1.0.2"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.6'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platform => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# gem "couchrest",        :git => "git://github.com/concord-consortium/couchrest.git", :branch => "works-with-rails3.2"
gem "couchrest_model", "~> 2.0.0.beta2"

def darwin_only(require_as)
  RbConfig::CONFIG['host_os'] =~ /darwin/ && require_as
end

def linux_only(require_as)
  RbConfig::CONFIG['host_os'] =~ /linux/ && require_as
end

def windows_only(require_as)
  RbConfig::CONFIG['host_os'] =~ /mingw|mswin/i && require_as
end

group :development do
  gem "guard",       "~> 1.6.2"
  gem "guard-rspec", "~> 2.4.1"
  # FS Notification libraries for guard (non-polling)
  gem 'rb-fsevent', "~> 0.9.3", :require => darwin_only('rb-fsevent')
  gem 'rb-inotify', "~> 0.8.8", :require => linux_only('rb-inotify')
  gem 'wdm',        "~> 0.1.0", :require => windows_only('wdm')
  # Growl Notification Transport Protocol (used by guard)
  gem 'ruby_gntp',  "~> 0.3.4"
end

group :development, :test do
  # debuggers ...
  gem "debugger",    "~> 1.3.2"
  gem "pry"
  gem "pry-nav"
  gem "pry-stack_explorer"
  gem "awesome_print"
end

group :test do
  gem "rspec-rails"
  gem "webmock"
  gem "factory_girl_rails",  "~> 4.2.1"
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
