source 'https://rubygems.org'

gem 'rails', '3.2.11'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'thin',  '~> 1.3'

gem "haml",               "~> 3.1.7"
gem "sass",               "~> 3.2.1"
gem 'bourbon',            "~> 2.1.0"
gem 'neat',               "~> 0.4.2"
gem 'ruby-progressbar',   "~> 1.0.2"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platform => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# gem "couchrest",        :git => "git://github.com/concord-consortium/couchrest.git", :branch => "works-with-rails3.2"
gem "couchrest_model", "~> 2.0.0.beta2"


group :development do
  gem "guard",       "~> 1.6.1"
  gem "guard-rspec", "~> 2.4.0"
  gem "debugger"
  # FS Notification libraries for guard (non-polling)
  gem 'rb-inotify', :require => false
  gem 'rb-fsevent', :require => false
  gem 'rb-fchange', :require => false
end

group :test do
  gem "rspec-rails"
  gem "webmock"
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
