#!/usr/bin/env node

var converter = require('../src/helpers/md2d/mw-batch-converter'),
    sys = require('sys'),
    nConverted;

sys.print("converting MML files...");
// Convert outdated mml files only
nConverted = converter.convertMMLFolder(true, true);
sys.print("converted " + nConverted + " MML files.\n");
