#!/usr/bin/env node

var converter = require('../src/helpers/md2d/mw-batch-converter');
    fs        = require('fs'),
    path      = require('path'),
	  indexFile = path.normalize(path.dirname(require.main.filename) +
		          '/../public/imports/legacy-mw-content/legacyMMLRunnables.html');

converter.createCmlJsonIndex( indexFile );