#!/usr/bin/env node

var fs = require('fs');

// Process arguments.
// Skip node and script paths.
var args = process.argv.splice(2);
if (args.length < 2) {
	throw new Error("Usage: [input_files_list] -o output_file");
}
var outArgs = args.splice(-2);
if (outArgs[0] !== "-o") {
	throw new Error("Usage: [input_files_list] -o output_file");
}
// Prepare output.
var outputFile = outArgs[1];
var outputSource = "var lab = lab || {};\nlab.glsl = {};\n\n";

for (var i = 0, len = args.length; i < len; i += 1) {
  outputSource += "lab.glsl['" + args[i] + "'] = '\\\n";
  // For each line of input GLSL file.
	fs.readFileSync(args[i]).toString().split('\n').forEach(function (line) { 
    outputSource += line + "\\n\\\n";
	});
  outputSource += "';\n\n";
}

fs.writeFileSync(outputFile, outputSource);