#!/usr/bin/env node

// Simple script that converts HTML hex color (e.g. #ffffff) into color value used by MD2D elements.

var input = process.argv[2];

if (input[0] === '#') {
  input = input.substr(1);
}

var num = parseInt(input, 16);
num = num - Math.pow(2, 24);

console.log(input + ' => ' + num);
